services:
  frontend:
    image: nginx:stable-alpine
    container_name: u_agent_frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./uagent.top.pem:/etc/nginx/ssl/uagent.top.pem
      - ./uagent.top.key:/etc/nginx/ssl/uagent.top.key
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  backend:
    image: python:3.9-slim
    container_name: u_agent_backend
    working_dir: /app
    command: sh -c "pip install -r requirements.txt && gunicorn app.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - TZ=Asia/Shanghai
      - PYTHONUNBUFFERED=1
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge 