services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      tags:
        - "0.0.1"
    container_name: u_agent_frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./uagent.top.pem:/etc/nginx/ssl/uagent.top.pem
      - ./uagent.top.key:/etc/nginx/ssl/uagent.top.key
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      tags:
        - "0.0.1"
    container_name: u_agent_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
      - backend-uploads:/app/uploads
      - backend-static:/app/static/images
    environment:
      - TZ=Asia/Shanghai
      - PYTHONUNBUFFERED=1
    networks:
      - app-network
    restart: unless-stopped
volumes:
  backend-uploads:
  backend-static:
networks:
  app-network:
    driver: bridge