version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: u_agent_frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./uagent.top.pem:/etc/nginx/ssl/uagent.top.pem
      - ./uagent.top.key:/etc/nginx/ssl/uagent.top.key
    environment:
      - NODE_ENV=production
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--no-check-certificate", "--spider", "https://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: u_agent_backend
    ports:
      - "8000:8000"
    volumes:
      - backend-uploads:/app/uploads
      - backend-static:/app/static
    environment:
      - TZ=Asia/Shanghai
      - PYTHONUNBUFFERED=1
      - DEBUG=false
      - HOST=0.0.0.0
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2'
        reservations:
          memory: 2G
    networks:
      - app-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  backend-uploads:
  backend-static:

networks:
  app-network:
    driver: bridge 